# Usernames of channels the account has joined (with or without @).
# Example:
# channels:
#   - username: "geopolitics_prime"
#   - "another_channel"

channels:
  - username: BBC_News0
  - username: aljazeeraglobal
  - username: sitrep
  - username: Rueters
  - username: associated_press_news
  - username: molfar_global
  - username: OSINTdefender
  - username: ClashReport



